services:
  crud:
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=crud.py         # Le decimos a Flask cómo se llama tu archivo
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./crud:/app
    # ESTA ES LA MAGIA: Reemplaza a Gunicorn solo en desarrollo
    command: flask run --host=0.0.0.0 --port=8000